FROM golang:1.11-alpine3.8 as build
ENV GO111MODULE=on
WORKDIR /go/src/app
COPY . .
RUN apk add --no-cache --update build-base git && \
    GOOS=linux GOARCH=__GOLANG_ARCH__ make build

FROM __BASEIMAGE_ARCH__/alpine:3.8
COPY --from=build /go/src/app/seattlewaste2mqtt /usr/local/bin/seattlewaste2mqtt
VOLUME /config
RUN apk add --no-cache --update ca-certificates
CMD ["seattlewaste2mqtt", "-c", "/config/config.yaml"]
