// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeCollectionLookup() *CollectionLookup {
	config := NewConfig()
	mqttFuncWrapper := NewMQTTFuncWrapper()
	collectionLookup := NewCollectionLookup(config, mqttFuncWrapper)
	return collectionLookup
}
