// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func Initialize() *SeattleWaste2Mqtt {
	config := NewConfig()
	mqttFuncWrapper := NewMQTTFuncWrapper()
	seattleWaste2Mqtt := NewSeattleWaste2Mqtt(config, mqttFuncWrapper)
	return seattleWaste2Mqtt
}
